### PR TITLE
Enhancement CLIENT_DEPRECATE_EOF

### PR DESCRIPTION
**Pull request by shiyuhang0**
Optimize https://github.com/denodrivers/mysql/pull/139

when CLIENT_DEPRECATE_EOF is set. EOF_Packet can also be Ok_Packet.

https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_com_query_response_text_resultset.html

### CODE REVIEW

**Comment by shiyuhang0** [comment]
I also have a question about this code in connection.ts
```
  this.capabilities = handshakePacket.serverCapabilities;
```
The capabilities should be `handshakePacket.serverCapabilities` or HandshakeResponse's client_flag?

**Comment by shiyuhang0** [comment]
@lideming PTAL

**Comment by lideming** [comment]
But I wonder why it works without this change.

> The capabilities should be handshakePacket.serverCapabilities or [HandshakeResponse's client_flag](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_connection_phase_packets_protocol_handshake_response.html#sect_protocol_connection_phase_packets_protocol_handshake_response41)?

I think both should work. As we response with the flags that server advertised and client recognized.

**Comment by shiyuhang0** [comment]
Because we judge EOF package by 0xFE. And OK packet can be either 0x00 or 0xFE.
When the client and server both support CLIENT_DEPRECATE_EOF, serve will send OK packet. If it is 0xFE ,it happens to work. But if it is 0x00, I think we can't work.

**Review by lideming — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
