### PR TITLE
Support Authentication Method Mismatch

### PR DESCRIPTION
**Pull request by shiyuhang0**
https://github.com/denodrivers/mysql/issues/113

This pr supports the Authentication Method Mismatch described as https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_connection_phase.html

### CODE REVIEW

**Comment by shiyuhang0** [comment]
@lideming PTAL
But I don't know how to test it. I test it locally by [TiDB Cloud Serverless Tier](https://www.pingcap.com/tidb-cloud/) which always trigger the `auth method mismacth` phase.

**Comment by lideming** [comment]
Please run `deno fmt` to make CI pass.

**Comment by shiyuhang0** [comment]
I found the test failed with the latest MariaDB. If it is my fault, please let me known

**Comment by lideming** [comment]
Not your fault. It failed on the master branch too. Seems that something changed about the EOF packet in the latest mariadb... I think we can temporarily disable `mariadb:latest` and see if other tests pass:
https://github.com/lideming/deno_mysql/blob/master/.github/workflows/ci.yml#L35

**Comment by lideming** [comment]
LGTM. Thanks for your contribution!

**Pull request merged**
