### PR TITLE
Use template literals

### PR DESCRIPTION
**Pull request by algj**
I haven't tested it. Please test it if it works correctly.

Usage:
```ts
import { Client, SQL } from "https://deno.land/x/mysql/mod.ts";
const client = await new Client().connect({...options...});

client.query(SQL`select $${"name"} from $${"users"} where id = ${5}`);
// is exactly the same as:
client.query("select  ??  from  ??  where id =  ?", [ "name", "users", 5 ]);
```

### CODE REVIEW

**Comment by wenjoy** [comment]
Tests fail on my try. 
Have u ever run the Unit Test though? Do they pass or not?

**Comment by algiuxass** [comment]
> Have u ever run the Unit Test though? Do they pass or not?

I haven't tested anything. If you get any error, tell me.

**Comment by wenjoy** [comment]
@algiuxass Just run ` deno test --allow-env --allow-net test.ts`. Basically , we should make sure the coming code will not break the unit  test.

**Comment by manyuanrong** [comment]
We always hope that new changes can be covered by corresponding tests

**Pull request closed without merging**
